#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: prepare <DAYNUM>"
    exit 1
fi

function overwrite_check() {
    if [ -e "$1" ]; then
        echo "Skipping '$(basename $1)' to prevent overwrite.."
        return 1
    else
        return 0
    fi
}

function load() {
    echo -n "$1.."
    "$HELPER_ROOT/scripts/scrape" ${@:2}
    rv=$?
    if [ $rv -eq 0 ]; then
        echo "done"
    else
        echo "fail"
    fi
    return $rv
}

function copy() {
    echo "Adding '$(basename $2)'.."
    cp -r "$1" "$2"
}

if [[ "$1" =~ "[0-9]+" ]]; then
    echo "Not a number"
    exit 1
fi

DAYNUM="$1"
DAYDIR="$SOLUTIONS_ROOT/$SRCDIR/day$DAYNUM"

[ ! -e "$DAYDIR" ] && ( echo "Initializing directory.."; mkdir -p "$DAYDIR" )

IFS=$'\x0a'
for f in $TEMPLATE_FILES; do
    [[ "$f" == "" ]] && continue;
    if="$(echo $f | cut -d':' -f1)"
    of="$(echo $f | cut -d':' -f2)"
    if [ -e "$SOLUTIONS_ROOT/$TEMPLATE_DIR/$if" ]; then
        overwrite_check "$DAYDIR/$of" && \
            copy "$SOLUTIONS_ROOT/$TEMPLATE_DIR/$if" "$DAYDIR/$of";
    else
        echo "Skipping '$(basename $if)' as unavailable.."
    fi
done

overwrite_check "$DAYDIR/input" && load "Loading problem input" $DAYNUM input
overwrite_check "$DAYDIR/part1" && load "Loading first problem text"  $DAYNUM part 1
overwrite_check "$DAYDIR/part2" && load "Loading second problem text" $DAYNUM part 2
