#!/usr/bin/env python3

import requests, sys, os, json
from bs4 import BeautifulSoup

if len(sys.argv) != 4:
    print("Usage: submit <day> <part> <answer>")
    sys.exit(1)

daynum = sys.argv[1]
lvlnum = sys.argv[2]
answer = sys.argv[3]

year = os.getenv("AOCYEAR")
url = f"https://adventofcode.com/{year}/day/{daynum}/answer"
reporoot = os.getenv("HELPER_ROOT")
headers = json.loads(open(f"{reporoot}/data/headers").read())
data = { 'level': lvlnum, 'answer': answer }

r = requests.post(url, headers=headers, data=data)
soup = BeautifulSoup(r.text, "html.parser")
print(soup.select_one("main").text)
